# Generated by Django 6.0.4 on 2026-08-15 05:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_offre', models.CharField(choices=[('intra', 'Intra'), ('inter', 'Inter'), ('mission_longue', 'Mission longue')], max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('cloturee', 'Clôturée'), ('archivee', 'Archivée')], default='brouillon', max_length=20)),
                ('localisation', models.CharField(blank=True, max_length=120)),
                ('duree', models.CharField(blank=True, editable=False, max_length=80, null=True)),
                ('nb_max_de_candidatures', models.PositiveIntegerField(default=30)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('competences', models.ManyToManyField(blank=True, related_name='offres', to='core.competence')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='account.institution')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
