# Generated by Django 6.0.4 on 2026-08-15 05:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('formateur', 'Formateur'), ('institution', 'Institution'), ('admin', 'Administrateur')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('civilite', models.CharField(blank=True, choices=[('m', 'M.'), ('mme', 'Mme'), ('autre', 'Autre / Préfère ne pas préciser')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'institution'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_institution', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_organisation', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('localisation_institution', models.CharField(blank=True, max_length=120)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('secteur', models.CharField(blank=True, help_text='Ex : Enseignement supérieur, E-santé', max_length=100)),
                ('taille_effectif', models.CharField(blank=True, help_text='Ex : 500+ collaborateurs', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'formateur'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_formateur', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('biographie', models.TextField(blank=True)),
                ('localisation_formateur', models.CharField(blank=True, max_length=120)),
                ('tarif_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('experience_annees', models.PositiveIntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('titre_professionnel', models.CharField(blank=True, max_length=150)),
                ('delai_reponse', models.CharField(blank=True, help_text='Ex : ~4h, ~1 jour', max_length=30)),
                ('disponibilite', models.CharField(blank=True, help_text='Ex : 2 sem., Immédiate', max_length=50)),
                ('langues', models.CharField(blank=True, help_text='Ex : FR, EN', max_length=100)),
                ('competences', models.ManyToManyField(blank=True, related_name='formateurs', to='core.competence')),
            ],
        ),
    ]
