# Generated by Django 6.0.4 on 2026-08-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
