# Generated by Django 6.0.4 on 2026-08-15 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.EmailField(help_text='Email utilisé pour la création du ticket (peut différer de celui du compte).', max_length=254)),
                ('gestsup_ticket_id', models.CharField(blank=True, max_length=20, null=True)),
                ('gestsup_url', models.CharField(blank=True, max_length=500, null=True)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('resolu', 'Résolu'), ('erreur', "Erreur d'envoi"), ('introuvable', 'Introuvable dans GestSup')], default='envoye', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'aide",
                'verbose_name_plural': "Demandes d'aide",
                'ordering': ['-created_at'],
            },
        ),
    ]
