# Generated by Django 6.0.4 on 2026-08-15 05:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('developpement', 'Développement'), ('data_ia', 'Data & IA'), ('design', 'Design'), ('cybersecurite', 'Cybersécurité'), ('management', 'Management'), ('cloud', 'Cloud'), ('autres', 'Autres')], max_length=50)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=120)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nb_places_max', models.PositiveIntegerField(default=20, verbose_name='Nombre de places maximum')),
                ('support_pdf', models.FileField(blank=True, null=True, upload_to='formations/supports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Support de formation (PDF)')),
                ('terminee_manuelle', models.BooleanField(default=False, verbose_name='Marquée terminée manuellement')),
                ('co_intervenants', models.ManyToManyField(blank=True, related_name='co_formateurs', to='account.formateur')),
                ('competences', models.ManyToManyField(blank=True, related_name='formations', to='core.competence')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateurs', to='account.formateur')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='confirmee', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formation.formation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_inscription'],
                'unique_together': {('formation', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='formations/attestations/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='formation.inscriptionformation')),
            ],
        ),
    ]
