# Generated by Django 6.0.4 on 2026-08-15 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('offre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('retiree', 'Retirée')], default='en_attente', max_length=20)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures/cv/')),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_decision', models.TextField(blank=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='account.formateur')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='offre.offre')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_candidature'],
                'constraints': [models.UniqueConstraint(fields=('offre_id', 'formateur_id'), name='unique_candidature_par_offre')],
            },
        ),
    ]
